### ISSUE TITLE
How to update (quickly)

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#80] opened 2017-12-03 08:11 UTC
When we have a new version...
We must copy the new files and RE-edit all the userChrome.css or there is a better method, more quickly?

**Comment by Aris-t2** [comment] 2017-12-03 08:58
Duplicate of https://github.com/Aris-t2/CustomCSSforFx/issues/64

**Closed by Aris-t2** 2017-12-03 08:58 UTC
Labels: duplicate
