### ISSUE TITLE
[Fx76+] Favorites bar: Issues with "arrows" in a folder

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#301] opened 2020-05-06 16:21 UTC
With the last update (Firefox 76), scroll arrows are gone from the folders in the favorites bar.
example:
![Immagine1](https://user-images.githubusercontent.com/33927879/81202070-588aa800-8fc6-11ea-9b78-44c1a74d8cd8.png)

here without CustomCSSforFx:
![Immagine2](https://user-images.githubusercontent.com/33927879/81202097-604a4c80-8fc6-11ea-96d5-b3ed7a6b8e2f.png)

**Comment by Aris-t2** [comment] 2020-05-06 20:39
Add all information required in 1-5 and delete this line and everything above it before submitting.


1. Describe the issue


2. What should have happened instead?


3. Steps to reproduce the issue?


4. SCREENSHOTS with/without this projects files (drag & drop images into this post)


5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']):
- OS & OS version: 
- OS theme (if not default): 
- DPI / HiDPI resolution: 
- Firefox version: 
- Firefox theme / lw-theme: 
- This projects 'settings' the issue occurs with:

**Comment by Aris-t2** [comment] 2020-05-06 20:59
The issue is caused by code inside `bookmark_icons_colorized.css`. Use this to fix it.

```css
#scrollbutton-up .toolbarbutton-icon,
#scrollbutton-down .toolbarbutton-icon {
  -moz-image-region: auto !important;
}
```

**Comment by gabri25ele** [comment] 2020-05-07 07:46
ok, added in bookmark_icons_colorized.css
it works fine
thanks

**Comment by Aris-t2** [comment] 2020-05-07 08:38
The code will be included in next update.

**Closed** 2020-05-07 22:07 UTC
Labels: BUG, fixed
