### ISSUE TITLE
Modify Context Menu (Right Click Menu)

### ISSUE THREAD

**Issue by chad-abizeid** [Aris-t2/CustomCSSforFx#89] opened 2017-12-13 18:50 UTC
Can someone please explain how to modify the context menu? It's absurd how crushed vertically the rows are. Why would Firefox do that? So dumb.

I used to use below CSS in Stylish awhile back...

```
/*===============================================
  CONTEXT MENUS
===============================================*/

menupopup.textbox-contextmenu,
popupset > menupopup,
popupset > menupopup menupopup,
popupset >*:not(menupopup) menupopup,
toolbarbutton:not(#bookmarks-menu-button):not(#alltabs-button):not(.bookmark-item)  menupopup,
#PlacesToolbar menupopup,
#main-menubar menupopup,
#sourceeditor-context
{
    -moz-appearance: none !important;
    background-color:#f2f2f2 !important;
    background-clip:padding-box!important;
    max-width:240px;
    border: 1px solid #ccc !important;
}
menupopup.textbox-contextmenu :-moz-any(menu,menuitem)[_moz-menuactive="true"],
popupset > menupopup  :-moz-any(menu,menuitem)[_moz-menuactive="true"]:not([id^="BMB"]),
popupset > menupopup  menupopup :-moz-any(menu,menuitem)[_moz-menuactive="true"]:not([id^="BMB"]),
popupset >*:not(menupopup) menupopup :-moz-any(menu,menuitem)[_moz-menuactive="true"],
toolbarbutton:not(#bookmarks-menu-button):not(#alltabs-button):not(.bookmark-item)  menupopup :-moz-any(menu,menuitem)[_moz-menuactive="true"],
#PlacesToolbar :-moz-any(menu,menuitem)[_moz-menuactive="true"],
#main-menubar menupopup :-moz-any(menu,menuitem)[_moz-menuactive="true"],
#sourceeditor-context :-moz-any(menu,menuitem)[_moz-menuactive="true"]
{
    background-color:#dadada !important;
    -moz-appearance: none !important;
}
menupopup.textbox-contextmenu :-moz-any([disabled="true"])[_moz-menuactive="true"],
popupset > menupopup  :-moz-any([disabled="true"])[_moz-menuactive="true"]:not([id^="BMB"]),
popupset > menupopup  menupopup :-moz-any([disabled="true"])[_moz-menuactive="true"]:not([id^="BMB"]),
popupset >*:not(menupopup) menupopup :-moz-any([disabled="true"])[_moz-menuactive="true"],
toolbarbutton:not(#bookmarks-menu-button):not(#alltabs-button):not(.bookmark-item)  menupopup :-moz-any([disabled="true"])[_moz-menuactive="true"],
#PlacesToolbar :-moz-any([disabled="true"])[_moz-menuactive="true"],
#main-menubar menupopup :-moz-any([disabled="true"])[_moz-menuactive="true"],
#sourceeditor-context :-moz-any([disabled="true"])[_moz-menuactive="true"]
#lpt_site-context-menu :-moz-any([disabled="true"])[_moz-menuactive="true"] {
    background-color: #F2F2F2 !important;
}
/*For Lastpass*/
#lpt_lastpass-compact-btn > menupopup :-moz-any(menu,menuitem)[_moz-menuactive="true"] > label.menu-iconic-text{
    color:#777;
}
#lpt_comp-bar-accts > * menuitem:hover,#lpt_lastpass-compact-menu-search-vbox menuitem:hover{
    color:#777 !important;
}
menupopup.textbox-contextmenu :-moz-any(menu,menuitem),
popupset > menupopup :-moz-any(menu,menuitem),
popupset >*:not(menupopup) menupopup :-moz-any(menu,menuitem),
toolbarbutton:not(#bookmarks-menu-button):not(#alltabs-button):not(.bookmark-item)  menupopup :-moz-any(menu,menuitem),
#PlacesToolbar :-moz-any(menu,menuitem),
#main-menubar menupopup :-moz-any(menu,menuitem),
#sourceeditor-context :-moz-any(menu,menuitem)
{
    padding-top:3px !important;
    padding-bottom:3px !important;
    padding-right:6px;
    padding-left:16px !important;
    border:1px solid transparent !important;
    -moz-appearance: none !important;
    font-size:14px;
    color: #333 !important;
}
/* For AllTabs Popup */
#alltabs-button menupopup {
    width: 280px !important;
}
#alltabs-button menu,#alltabs-button menuitem {
    font-size:14px !important;
    padding: 5px 0!important;
    max-width: unset !important;
}
#alltabs-button menu[_moz-menuactive="true"],
#alltabs-button menuitem[_moz-menuactive="true"]
{
    background-color:#dadada !important;
		-moz-appearance: none !important;
}
/* For Separator */
menupopup.textbox-contextmenu menuseparator,
popupset > menupopup menuseparator,
popupset > menupopup menupopup menuseparator,
popupset >*:not(menupopup) menupopup menuseparator,
toolbarbutton:not(#bookmarks-menu-button):not(#alltabs-button):not(.bookmark-item)  menupopup menuseparator,
#PlacesToolbar menupopup menuseparator,
#main-menubar menupopup menuseparator,
#sourceeditor-context menuseparator
{
    -moz-appearance: none !important;
    border-width: 1px 0 0 0;
    border-color: #CCC !important;
    padding:0px !important;
    margin:6px 10px 7px !important;
}
/* Hide Menu Icon Except CheckBox and Radio*/
menupopup.textbox-contextmenu :-moz-any(menu,menuitem):not([type="checkbox"]):not([type="radio"]):not(.bookmark-item) > hbox.menu-iconic-left,
popupset > menupopup :-moz-any(menu,menuitem):not([type="checkbox"]):not([type="radio"]):not(.bookmark-item) > hbox.menu-iconic-left,
popupset >*:not(menupopup) menupopup :-moz-any(menu,menuitem):not([type="checkbox"]):not([type="radio"]):not(.bookmark-item) > hbox.menu-iconic-left,
toolbarbutton:not(#bookmarks-menu-button):not(#alltabs-button):not(.bookmark-item)  menupopup :-moz-any(menu,menuitem):not([type="checkbox"]):not([type="radio"]):not(.bookmark-item) > hbox.menu-iconic-left,
#PlacesToolbar menupopup :-moz-any(menu,menuitem):not([type="checkbox"]):not([type="radio"]) > hbox.menu-iconic-left,
#main-menubar menupopup :-moz-any(menu,menuitem):not([type="checkbox"]):not([type="radio"]):not(.bookmark-item) > hbox.menu-iconic-left,
#sourceeditor-context :-moz-any(menu,menuitem):not([type="checkbox"]):not([type="radio"]):not(.bookmark-item) > hbox.menu-iconic-left
{
		display: none;
}
/* For menuitems and menus which aren't iconized */
menupopup.textbox-contextmenu :-moz-any(menu,menuitem) > .menu-text,
popupset > menupopup :-moz-any(menu,menuitem) > .menu-text,
popupset >*:not(menupopup) menupopup :-moz-any(menu,menuitem) > .menu-text,
toolbarbutton:not(#bookmarks-menu-button):not(#alltabs-button):not(.bookmark-item)  menupopup :-moz-any(menu,menuitem) > .menu-text,
#PlacesToolbar menupopup :-moz-any(menu,menuitem) > .menu-text,
#main-menubar menupopup :-moz-any(menu,menuitem) > .menu-text,
#sourceeditor-context :-moz-any(menu,menuitem) > .menu-text
{
    -moz-appearance: none !important;
    padding-left:0px !important;
}
/* For Context Navigation */
#context-navigation > menuitem > hbox.menu-iconic-left {
    display: -moz-box !important;
}
/* For Context Navigation */
#context-navigation > menuitem {
    padding: 0 !important;
}
````
![ff](https://user-images.githubusercontent.com/8635771/33956408-73d00aea-e00c-11e7-83a6-f7e2d411f45f.PNG)

**Comment by userOperaFF** [comment] 2017-12-13 19:48
Read this paragraph:

> ## How to find item ids and attributes?
> 
> Enable once:  
> 1\. Tools > WebDeveloper > Toggle Tools > Toolbox Options > Enable browser chrome and add-on debugging toolboxes  
> 2\. Tools > WebDeveloper > Toggle Tools > Toolbox Options > Enable remote debugging  
> 
> Hit `Ctrl+Alt+Shift+I` or open 'Tools > WebDeveloper > Browser Toolbox'.  
> 
> Inspect ui or web content.  
> 
> Force popups to stay open for inspection (⚠️  important function for menuitems ⚠️):  
> Click on 'disable popup auto hide' button (= button with four squares) on developer toolbars end.   
> 
> ## How to modify custom user styles?

And let's go to work amigo 😉

**Comment by Aris-t2** [comment] 2017-12-13 21:35
Duplicate of https://github.com/Aris-t2/CustomCSSforFx/issues/76
Continue there.

**Closed by Aris-t2** 2017-12-13 21:35 UTC
