### ISSUE TITLE
Incorrect color with default theme when tabs-toolbar is below the navigation toolbar

### ISSUE THREAD

**Issue by ao2** [Aris-t2/CustomCSSforFx#141] opened 2018-09-10 12:04 UTC
Hi,

in a default setup, with the tabs bar above the navigation toolbar, the tabs bar uses the color of the menu bar:
![tab-bar_on_top](https://user-images.githubusercontent.com/1249395/45295873-760d2300-b500-11e8-922d-cdb4eb725b65.png)

## Describe the issue

However when enabling `classic/css/tabs/tabs_below_navigation_toolbar.css` I get an unexpected color for the tabs bar with the default theme:
![tab-bar_below_navigation_toolbar_current](https://user-images.githubusercontent.com/1249395/45295896-87562f80-b500-11e8-8cad-9c6324466366.png)

## What should have happened instead?

I would have expected the tabs-bar to get the same color as the navigation (and bookmarks) toolbar (BTW this color is a little darker than the one of the menu bar):
![tab-bar_below_navigation_toolbar_expected](https://user-images.githubusercontent.com/1249395/45296082-2844ea80-b501-11e8-8c3e-f75db4d36852.png)

I will propose a fix for this.

## Steps to reproduce the issue?

Set up the default theme and put this in `userChrome.css`:
```css
@import "./CustomCSSforFx/classic/css/tabs/tabs_below_navigation_toolbar.css"; /**/ /* <-- tabs not on top */
```

## System information
- OS & OS version: Debian GNU/Linux - Unstable
- OS theme name: Adwaita, the default GTK theme (GTK+ 3.24.0)
- Firefox version: 62.0 (64 bit)
- Firefox theme: default theme

Thanks,
   Antonio

**Comment by Aris-t2** [comment] 2018-09-10 12:44
Thanks for reporting this. I now understand why you proposed the change for "tabs_below_navigation_toolbar.css" in your commit.

When I understand it correctly, you are using this projects files without importing "general_toolbar_colors.css" or any configuration files, right?
That is where the magic happens, where toolbar colors are set. They override all toolbar colors with "default" ones to avoid inconsistencies.

On next update "tabs_below_navigation_toolbar.css" will get extended code to set toolbar colors. This should avoid your issue.

<details> <summary> new "tabs_below_navigation_toolbar.css" </summary>

```css

/* Firefox Quantum userChrome.css tweaks ************************************************/
/* Github: https://github.com/aris-t2/customcssforfx ************************************/
/****************************************************************************************/


:root {
  --colored_menubar_background_image: linear-gradient(#f9f9fa,#f9f9fa);
  --general_toolbar_color_toolbars: linear-gradient(#f9f9fa,#f9f9fa);
  --general_toolbar_color_navbar: linear-gradient(#f9f9fa,#f9f9fa);
  --tabs_toolbar_color_tabs_not_on_top: linear-gradient(#f9f9fa,#f9f9fa);
  --tabs_toolbar_border-tnot_normal_mode_size: 1px;
  --tabs_toolbar_border-tnot_normal_mode: var(--tabs-border-color);
  --classic_squared_tabs_tab_text_color: black;
  --classic_squared_tabs_tab_text_shadow: transparent;
  --tab-min-height_tnot: 32px;
}

:root[uidensity=compact]  {
  --tab-min-height_tnot: 28px;
}

:root[uidensity=touch] {
  --tab-min-height_tnot: 40px;
}

/* tabs toolbar adjustment */
#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar, 
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#TabsToolbar {
  -moz-padding-start: 2px !important;
}

#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar:-moz-lwtheme, 
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar:-moz-lwtheme,
#main-window[uidensity=compact][tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar:-moz-lwtheme,
#main-window[uidensity=compact][tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar:-moz-lwtheme,
#TabsToolbar:-moz-lwtheme,
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[sizemode="maximized"] #TabsToolbar,
#main-window[tabsintitlebar]:not([style*='--lwt-header-image']):-moz-lwtheme #navigator-toolbox #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar, 
#main-window[tabsintitlebar][sizemode="maximized"]:not([style*='--lwt-header-image']):-moz-lwtheme #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar]:not([style*='--lwt-header-image']):-moz-lwtheme #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="maximized"]:not([style*='--lwt-header-image']):-moz-lwtheme #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[tabsintitlebar]:not([style*='--lwt-header-image']):-moz-lwtheme #TabsToolbar {
  -moz-padding-start: 0px !important;
}

#main-window[tabsintitlebar][sizemode="normal"]:not([sizemode="fullscreen"]) #TabsToolbar {
  margin-top: 0px !important;
}

#main-window[tabsintitlebar][sizemode="normal"][chromehidden~="menubar"] #TabsToolbar,
#main-window[tabsintitlebar][sizemode="normal"] #toolbar-menubar[autohide="true"][inactive] + #TabsToolbar,
#main-window[tabsintitlebar][sizemode="maximized"][chromehidden~="menubar"] #TabsToolbar,
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive] + #TabsToolbar {
  padding-top: 0px !important;
}

#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"]:not([inactive="true"]) ~ #TabsToolbar,
#main-window[tabsintitlebar] #toolbar-menubar[autohide="false"] ~ #TabsToolbar{
  margin-top: 0px !important;
}

/* tab title in titlebar support */
#main-window[tabsintitlebar][sizemode="normal"] #navigator-toolbox #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="normal"] #navigator-toolbox #TabsToolbar,
#main-window[tabsintitlebar][sizemode="maximized"] #navigator-toolbox #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="maximized"] #navigator-toolbox #TabsToolbar,
#main-window[tabsintitlebar][sizemode="normal"] #navigator-toolbox #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="normal"] #navigator-toolbox #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[tabsintitlebar][sizemode="maximized"] #navigator-toolbox #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar,
#main-window[uidensity=compact][tabsintitlebar][sizemode="maximized"] #navigator-toolbox #toolbar-menubar[autohide="true"][inactive="true"] ~ #TabsToolbar{
  margin-top: 0px !important;
}

/* titlebar button support */
#main-window[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive="true"] ~ #nav-bar{
  margin-top: 2px !important;
}

/* fix for application/hamburger button in titlebar */
#main-window[tabsintitlebar][sizemode="fullscreen"] #toolbar-menubar[autohide="true"][inactive="true"] ~ #nav-bar  #PanelUI-button {
  visibility: collapse !important;
}

#main-window[inDOMFullscreen="true"] #TabsToolbar {
  opacity: 0 !important;
}

/* tab height */
#tabbrowser-tabs,
#tabbrowser-tabs > .tabbrowser-arrowscrollbox,
.tabbrowser-tabs[positionpinnedtabs] > .tabbrowser-tab[pinned] {
  min-height: var(--tab-min-height_tnot) !important;
}

/* toolbar order (start) ************************************/
#print-preview-toolbar,
#printedit-toolbar,
#titlebar {
  -moz-box-ordinal-group: 0 !important;
}
#navigator-toolbox #toolbar-menubar {
  -moz-box-ordinal-group: 1 !important;
}
/* navigation toolbar */
#navigator-toolbox #nav-bar {
  -moz-box-ordinal-group: 2 !important;
}
/* bookmarks toolbar */
#navigator-toolbox #PersonalToolbar {
  -moz-box-ordinal-group: 3 !important;
}
/* 3rd party toolbars */
#navigator-toolbox toolbar {
  -moz-box-ordinal-group: 10 !important;
}
/* tabs toolbar */
#navigator-toolbox #TabsToolbar {
  -moz-box-ordinal-group: 100 !important;
}
/* toolbar order (end) **************************************/

/* toolbar colors */
#main-window:not([tabsintitlebar]) #toolbar-menubar:not(:-moz-lwtheme) {
  background-image: var(--colored_menubar_background_image) !important;
  border: 0px !important;
  margin-bottom: -1px !important;
}

#nav-bar:not(:-moz-lwtheme) {
  -moz-appearance: none !important;
  background: var(--general_toolbar_color_navbar, inherit) !important;
}

toolbar:not(#TabsToolbar):not(#toolbar-menubar):not(#nav-bar):not(:-moz-lwtheme) {
  -moz-appearance: none !important;
  background: var(--general_toolbar_color_toolbars, inherit) !important;
}
#TabsToolbar:not(:-moz-lwtheme){
  -moz-appearance: none !important;
  background-image: var(--tabs_toolbar_color_tabs_not_on_top) !important;
}

/* remove color overlay for lw-themes */
#main-window[style*='--lwt-header-image'] :-moz-any(#nav-bar,#PersonalToolbar,#TabsToolbar):-moz-lwtheme{
  background: unset !important;
}

/* adjust compact themes background color */
#main-window:not([style*='--lwt-header-image']) #TabsToolbar:-moz-lwtheme {
  -moz-appearance: none !important;
  background-image: linear-gradient(var(--toolbar-bgcolor),var(--toolbar-bgcolor)) !important;
}

#main-window:not(:-moz-lwtheme) #TabsToolbar :-moz-any(.tabs-newtab-button,.scrollbutton-up,.scrollbutton-down),
#main-window:not(:-moz-lwtheme) #TabsToolbar > toolbarbutton,
#main-window:not([style*='--lwt-header-image']):-moz-lwtheme:-moz-lwtheme-darktext #TabsToolbar :-moz-any(.tabs-newtab-button,.scrollbutton-up,.scrollbutton-down),
#main-window:not([style*='--lwt-header-image']):-moz-lwtheme:-moz-lwtheme-darktext #TabsToolbar > toolbarbutton {
  fill: black !important;
  color: black !important;
}

/* toolbar borders */
#main-window #navigator-toolbox::after {
  opacity: 0 !important;
}

#TabsToolbar{
  margin-bottom: 0px !important;
  border-bottom: 1px solid #5f7181 !important;
}

#main-window[sizemode="normal"] #navigator-toolbox :-moz-any(#nav-bar,#PersonalToolbar,#TabsToolbar) {
  border-left: var(--tabs_toolbar_border-tnot_normal_mode_size) solid var(--tabs_toolbar_border-tnot_normal_mode) !important;
  border-right: var(--tabs_toolbar_border-tnot_normal_mode_size) solid var(--tabs_toolbar_border-tnot_normal_mode) !important;
  background-clip: padding-box !important;
}

#main-window[sizemode="maximized"] #navigator-toolbox :-moz-any(#nav-bar,#PersonalToolbar,#TabsToolbar) {
  border-left: 0px !important;
  border-right: 0px !important;
}

#main-window[style*='--lwt-header-image'][sizemode="normal"] #navigator-toolbox :-moz-any(#nav-bar,#PersonalToolbar,#TabsToolbar):-moz-lwtheme,
#main-window[style*='--lwt-header-image'][sizemode="maximized"] #navigator-toolbox :-moz-any(#nav-bar,#PersonalToolbar,#TabsToolbar):-moz-lwtheme {
  border-top: 0px !important;
  border-left: 0px !important;
  border-right: 0px !important;
}

#main-window:not([style*='--lwt-header-image']):-moz-lwtheme-brighttext #TabsToolbar:-moz-lwtheme {
  border-bottom: 1px solid #323234 !important;
}

#main-window:not([style*='--lwt-header-image']):-moz-lwtheme:-moz-lwtheme-brighttext #TabsToolbar:-moz-lwtheme {
  border-bottom: 1px solid #323234 !important;
}

#main-window:not([sizemode="fullscreen"])[tabsintitlebar] #TabsToolbar{
  -moz-margin-end: 0px !important;
}

#main-window[tabsintitlebar] #TabsToolbar .titlebar-placeholder{
  visibility: collapse !important;
}

#main-window[tabsintitlebar][sizemode="normal"] #toolbar-menubar[autohide="true"][inactive="true"] {
  margin-top: 21px !important;
}
#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] {
  margin-top: 20px !important;
}

#tabbrowser-tabs .tab-drop-indicator {
  margin-bottom: 0px !important;
}

#PersonalToolbar:-moz-lwtheme,
#nav-bar:-moz-lwtheme {
  background-image: none !important;
  box-shadow: none !important;
  border-top: none !important;
  border-bottom: none !important;
}

/* remove tab fog */
#TabsToolbar:not(:-moz-lwtheme),
#TabsToolbar:not(:-moz-lwtheme)::before,
#TabsToolbar:not(:-moz-lwtheme)::after {
  box-shadow: unset !important;
}

/* remove 'dragging tab' margin/padding nonsense */
#TabsToolbar[movingtab] {
  padding-bottom: unset !important;
}

#TabsToolbar[movingtab] > .tabbrowser-tabs {
  padding-bottom: unset !important;
  margin-bottom: unset !important;
}

#TabsToolbar[movingtab] + #nav-bar {
  margin-top: unset !important;
}

/* scroll buttons */
#TabsToolbar:not(:-moz-lwtheme) #alltabs-button,
#TabsToolbar:not(:-moz-lwtheme) .tabbrowser-arrowscrollbox > .scrollbutton-up,
#TabsToolbar:not(:-moz-lwtheme) .tabbrowser-arrowscrollbox > .scrollbutton-down {
  fill: black !important;
}

/* Fx58+ titlebar placeholders */
#TabsToolbar .titlebar-placeholder[type="pre-tabs"],
#TabsToolbar .titlebar-placeholder[type="post-tabs"]{
  display: none !important;
}

@media (-moz-os-version: windows-win10) {
	#main-window[tabsintitlebar][sizemode="normal"] #toolbar-menubar[autohide="true"][inactive="true"] {
	  margin-top: 30px !important;
	}
	#main-window[tabsintitlebar][sizemode="maximized"] #toolbar-menubar[autohide="true"][inactive="true"] {
	  margin-top: 30px !important;
	}
}

@media (-moz-windows-classic) {

	/* tweaks for Windows Classic theme */
	#nav-bar:not(:-moz-lwtheme),
	#PersonalToolbar:not(:-moz-lwtheme),
	#main-window:not([tabsintitlebar])  #TabsToolbar:not(:-moz-lwtheme) {
	  border-left: unset !important;
	  border-right: unset !important;
	  background: unset !important;
	}

	#main-window[sizemode="normal"] #navigator-toolbox :-moz-any(#nav-bar,#PersonalToolbar,#TabsToolbar) {
	  border-left: 0px !important;
	  border-right: 0px !important;
	}

	#main-window:not([tabsintitlebar]) #toolbar-menubar:not(:-moz-lwtheme) {
	  background: unset !important;
	  box-shadow: unset !important;
	  border-bottom: unset !important;
	}

	#main-window:not([tabsintitlebar]):not(:-moz-lwtheme) #navigator-toolbox,
	#main-window:not([tabsintitlebar]):not(:-moz-lwtheme) #nav-bar,
	#main-window:not([tabsintitlebar]):not(:-moz-lwtheme) #navigator-toolbox::before,
	#main-window:not([tabsintitlebar]):not(:-moz-lwtheme) #nav-bar::before,
	#main-window:not([tabsintitlebar]):not(:-moz-lwtheme) #navigator-toolbox::after,
	#main-window:not([tabsintitlebar]):not(:-moz-lwtheme) #nav-bar::after {
	  background: unset !important;
	  box-shadow: unset !important;
	  border: unset !important;
	  border-image: unset !important;
	}

	#main-window:not([tabsintitlebar]) toolbar:not(#TabsToolbar):not(#toolbar-menubar):not(#nav-bar):not(:-moz-lwtheme) {
	  background: unset !important;
	}

}

/* tab text colors */
#TabsToolbar:not(:-moz-lwtheme) .tabbrowser-tab {
  color: var(--classic_squared_tabs_tab_text_color) !important;
  text-shadow: 1px 1px 1px var(--classic_squared_tabs_tab_text_shadow) !important;
}

/* fix Windows 7s default tab background (remove dark purple bg color)*/
@media (-moz-os-version: windows-win7) {
  @media (-moz-windows-default-theme) {
    .tabbrowser-tab:not([selected]):not(:hover):not(:-moz-lwtheme) {
      background-color: #e3e4e6 !important;
    }
	.tabbrowser-tab:not([selected]):hover:not(:-moz-lwtheme) {
      background-color: #cccdcf !important;
    }

  }
}
```
</details>

**Comment by ao2** [comment] 2018-09-10 13:34
Ah, I see.

Yes, I was not using `general_toolbar_colors.css` nor any configuration files because I wanted to diverge as little as possible from the default look and use a minimal `userChrome.css`.

Now I see that using `general_toolbar_colors.css` does make the look consistent, but it's still different from the original default theme.

For my isolated case I was going to propose the following patch:
```diff
diff --git a/classic/css/tabs/tabs_below_navigation_toolbar.css b/classic/css/tabs/tabs_below_navigation_toolbar.css
index 036f6df..d0864fb 100644
--- a/classic/css/tabs/tabs_below_navigation_toolbar.css
+++ b/classic/css/tabs/tabs_below_navigation_toolbar.css
@@ -4,7 +4,7 @@


 :root {
-  --tabs_toolbar_color_tabs_not_on_top: linear-gradient(#f9f9fa,#f9f9fa);
+  --tabs_toolbar_color_tabs_not_on_top: var(--toolbar-bgimage);
   --tabs_toolbar_border-tnot_normal_mode_size: 1px;
   --tabs_toolbar_border-tnot_normal_mode: var(--tabs-border-color);
   --classic_squared_tabs_tab_text_color: black;
```

Which, as I now understand, would break users who relay on `general_toolbar_colors.css`.

For now I can override the single variable in my own `userChrome.css`, i.e.:
```css
@import "./CustomCSSforFx/classic/css/tabs/tabs_below_navigation_toolbar.css"; /**/ /* <-- tabs not on top */
:root {
  /* the tabs toolbar color from CustomCSSforFx if different from the default toolbar color */
  --tabs_toolbar_color_tabs_not_on_top: var(--toolbar-bgimage) !important; /**/
}
```

BTW I tried the new file you pasted and it does not seem to change much, maybe there are some other changes which go along with it in the other files? Like you do not override the color anymore in `classic/css/tabs/tabs_below_navigation_toolbar.css`?

Just curios, why do you override default colors with custom ones in  `general_toolbar_colors.css`?
Could the default variable values be the ones from the browser style?

Thanks,
   Antonio

**Comment by Aris-t2** [comment] 2018-09-10 15:39
The problem is the amount of different OS theme variations. Colors of top toolbar areas are not equal for all toolbars. On Windows for example tabs and menu toolbar use different colors, if OS titlebar is enabled or not. Moving tabs toolbar below other toolbar keeps that "default" color, which is different from navigation toolbar or bookmarks toolbar.
It is also impossible to catch all toolbar colors with one variable. Although it seems to be created for exactly that purpose `var(--toolbar-bgimage)` is just a slightly transparent blur/shadow on top of the default window/top toolbar background. Look how it is defined inside browser.css.
And that is the case why I do not use var(--toolbar-bgimage).

The idea behind this project was to replicate CTR or at least what is still possible with CSS. Therefore all files have to play along. Using only "some" of this project files might create inconsistencies and this required a way of fixing them. I don't say adding a solid color in this case is the best solution, but it at least solves major color mismatches.

**Comment by ao2** [comment] 2018-09-10 16:30
OK, I didn't know about other OSes as I only tested on linux.

I guess with the new `tabs_below_navigation_toolbar.css` you pasted, an acceptable solution for me, **on linux**, is to override the colors in my `userChrome.css`, like that:
```css
:root {
  /* the toolbar colors from CustomCSSforFx are different from the original ones */
  --colored_menubar_background_image: var(--toolbar-bgimage) !important; /**/
  --general_toolbar_color_toolbars: var(--toolbar-bgimage) !important; /**/
  --general_toolbar_color_navbar: var(--toolbar-bgimage) !important; /**/
  --tabs_toolbar_color_tabs_not_on_top: var(--toolbar-bgimage) !important; /**/
}
```

With that I guess the issue can be closed when the new changes land in master.

Thank you,
   Antonio

**Comment by Aris-t2** [comment] 2018-09-12 08:57
This was the exact idea behind this move.

For those, who use the whole package, configuration files can be created/edited like this too.

**Comment by Aris-t2** [comment] 2018-09-15 13:28
Fixed on latest release.

**Closed by Aris-t2** 2018-09-15 13:28 UTC
