### ISSUE TITLE
[Fx 108] tabs_below_navigation_toolbar_alt.css: Menu bar centered and no "show more bookmarks button" icon

### ISSUE THREAD

**Issue by Grzdacz** [Aris-t2/CustomCSSforFx#509] opened 2022-11-18 20:26 UTC
1. Issue description:
When 

- "TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS/Alternative for multi-lined tabs" - enabled
- "MULTIROW / multi lined tabs - EXPERIMENTAL" - enabled

Menubar is centered and arrow for opening of hidden bookmarks on the right side of bookmark bar is missing (dot is only visible)

When 
"TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS/Alternative for multi-lined tabs" - disabled
everythig is OK.

2. Does the issue occur with latest CustomCSSforFx release?
Yes, with 4.2.4.

3. Steps to reproduce the issue: 
As described in 1.:
- "TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS/Alternative for multi-lined tabs" - enabled
- "MULTIROW / multi lined tabs - EXPERIMENTAL" - enabled

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![Aris-t2_issue_crop](https://user-images.githubusercontent.com/118398042/202795147-5d1a5ca9-b1a8-4868-95a4-780a3c80a1e0.jpg)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
(Custom CSS files will only work, if this pref is set to true!)
Yes, it is

6. System information
- OS & OS version: Windows 11
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 108 b3
- Firefox theme (e.g. default, dark, 'theme name & link'): system - automatic
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: 4.2.3v2 & 4.2.4

**Comment by glennpc** [comment] 2022-11-18 21:56
I'm having the same issue with Fx 108. 

https://github.com/Aris-t2/CustomCSSforFx/discussions/454#discussioncomment-4180133

**Comment by Aris-t2** [comment] 2022-11-19 00:46
The bug is with menubars "centered" position is caused by `tabs_below_navigation_toolbar_alt.css` line 331.
Replace `display: block !important;` with `display: flex !important;` for now.

**Comment by glennpc** [comment] 2022-11-19 01:50
Thanks @Aris-t2 that fixed it!

**Comment by Grzdacz** [comment] 2022-11-19 06:53
Thank you, it worked.

Problem with the "Show more bookmarks" button remained.

> arrow for opening of hidden bookmarks on the right side of bookmark bar is missing (dot is only visible)

![Aris-t2_issue_2_Show more bookmarks_OK](https://user-images.githubusercontent.com/118398042/202838589-30eab768-0417-4496-a7ca-5568c1e3689f.jpg)
![Aris-t2_issue_2_Show more bookmarks_no_icon](https://user-images.githubusercontent.com/118398042/202838592-5f39eb44-0bcf-45a2-9c88-df199b54ed9f.jpg)

**Comment by Aris-t2** [comment] 2022-11-21 18:26
I can not reproduce the issue with `"Show more bookmarks" button`.

**Comment by Grzdacz** [comment] 2022-11-21 19:08
I clicked through all the settings that I change from the original and found that enabling this setting

`@import "./css/generalui/bookmarks_smaller_more_bookmarks_icon.css"; /**/`

makes this icon disappear

**Comment by Aris-t2** [comment] 2022-11-25 15:19
@Grzdacz 
This is fixed on 4.2.5: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.2.5

If something still does not work, post here and I will reopen the issue.

**Closed by Aris-t2** 2022-11-25 15:19 UTC
Labels: BUG, WORKAROUND
