### ISSUE TITLE
Firefox 133 broke the look of my Firefox, and updating this mod caused additional issues.

### ISSUE THREAD

**Issue by Nicholas-Steel** [Aris-t2/CustomCSSforFx#708] opened 2024-11-27 07:56 UTC
1. Does the issue occur without any files inside /chrome/ folder? **No.**
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
[chrome.zip](https://github.com/user-attachments/files/17930799/chrome.zip) **Here is the contents of my Chrome folder, the issue is *I think clearly* conveyed in the images further down in this report.**

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)? **Yes.**
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-

4. Screenshots showing the issue (drag & drop images into this post):
So far I've noticed (after updating these tweaks) the Inactive tabs are the wrong colour, Active tab is the wrong colour, Close Tab button on the Active Tab is invisible, gray background in Address Bar and Search Bar.
![image](https://github.com/user-attachments/assets/952dc8f8-5685-48bf-950c-f02e9fe09e10)
The popup for Autocompleting a URL in the Address Bar is also broken, it's positioned higher and takes up entire width of display as seen in the below image (the narrow white line at the very top middle of the image is a bug with the Windows Snipping tool in Windows 10 and should be ignored).
![image](https://github.com/user-attachments/assets/6489a343-a019-4ef5-96af-5b4a42e2f79e)

6. System information
- OS & OS version: **Windows 10 22H2**
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): **"Make Text Bigger" in PC Setings -> Ease of Access is set to 120%**
- Firefox version: **133**
- Firefox theme (e.g. default, build in light/dark, external theme + link): **System Theme/Auto**

If this is wrong use of Issue Reporting than let me know where I should go to discuss this kinda situation.

**Comment by Aris-t2** [comment] 2024-11-27 17:15
You have to get and use the latest release of this projects files.
Rebuild your userChrome based on the latest userChrome.css

Some things I enabled during tests with your setup:
menubar_color.css
tabs_below_navigation_toolbar_fx133.css
megabar_expanding_breakout_disabled_fx133.css
urlbar_background_color.css

![image](https://github.com/user-attachments/assets/2ede5d1f-9377-409c-923d-9848baf073b7)
![image](https://github.com/user-attachments/assets/adb4be41-6986-4819-91d8-1d79d1dc3738)

Not sure why your tab text looks like that. Start with a clean setup and enabled everything step by step.

**Comment by Nicholas-Steel** [comment] 2024-11-28 01:37
hmm, I thought \config\ folder and the userChrome.css and userContent.css files don't usually need updating (since there's no easy way to do that that keeps your changes), just updating the css and maybe the images folders are usually all that needs to be done.

Looking at my copy of userChrome.css and the latest copy I... guess things have changed quite a bit since v4.1.3 and new entries may have been added/files renamed.

**Comment by Aris-t2** [comment] 2024-11-28 15:50
Most of the time its is enough to just update the /css/ folder, but not this time.

**Comment by Nicholas-Steel** [comment] 2024-11-28 18:47
Hmm, well based on the changelog for v4.6.1 and v4.6.2 as well as the variables you'd previously mentioned I tried replacing the **config**, **css** and **image** folders with 4.6.2 and then updating the following values in userChrome.css to their Firefox 133 equivalents:

@import "./css/tabs/tabs_below_navigation_toolbar_fx133.css"; /**/
@import "./css/locationbar/megabar_expanding_breakout_disabled_fx133.css"; /**/

I also added this variable:
@import "./css/locationbar/urlbar_background_color.css

This:
Did not fix the colouring issues with the tab bar
Fixed the URL & search bars having a gray background
Fixed the Megabar popup being too wide and wrongly positioned

tabs_below_navigation_toolbar_fx133.css also causes the Menu Bar to be moved up and partially covered by the Title Bar, this doesn't happen if I use the regular tabs_below_navigation_toolbar.css which seems to work fine with regards to positioning and makes me curious as to why a 133 version needed to be made...
![image](https://github.com/user-attachments/assets/498a4032-ccbc-4011-b3dd-baabb60ab4a0)

**Comment by Aris-t2** [comment] 2024-11-29 15:47
Maybe this is related you your OS theme/colors. Could you try to set a different OS/accent color than black?

It is also possible to override tab text colors using `custom_tab_text_settings.css`.

**Comment by Nicholas-Steel** [comment] 2024-11-29 23:38
Just seems odd for Firefox 133 to need more work to keep it looking like it was, the only custom tweaks I've made that aren't a part of CustomCSSforFx are located at the very bottom of userChrome.css, in my_userChrome.css and in user.js

There's one tweak in the userChrome.css because it doesn't seem to work if I put that one in the my_userChrome.css file (dunno why). it's kinda broken though, it causes the Search Box and add-on icons to the right of the URL Bar to disappear if I fullscreen and then restore a _embedded_ Youtube video, re-entering fullscreen with F11 and then hitting F11 again restores them.

Here's a copy of my user.js file: [user.zip](https://github.com/user-attachments/files/17963494/user.zip)

**Comment by Aris-t2** [comment] 2024-11-30 09:16
Lets try a different approach.

1. Download and setup [PortableFirefox](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%20133.0/FirefoxPortable_133.0_English.paf.exe/download).

2. Start `FirefoxPortable.exe` and enable `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config`.

3. Create `/chrome/` folder and extract [latest release (zip file) from here](https://github.com/Aris-t2/CustomCSSforFx/releases) to it. 
![image](https://github.com/user-attachments/assets/c047c936-d8f7-4b0c-b92d-9900344625be)

4. Start `FirefoxPortable.exe` , take and post a screenshot of the window showing this projects default setup (looks like this for me).
![image](https://github.com/user-attachments/assets/013db4a2-21f5-4ee9-ab79-25af5a40c61d)

5. Enable `tabs_below_navigation_toolbar_fx133.css`, restart Firefox and post a screenshot of the result (looks like this for me). 
![image](https://github.com/user-attachments/assets/ca363463-57ab-4aa9-a4a7-f420ca2d7231)


This is were we would start troubeshooting.

**Comment by joefiesta** [comment] 2024-11-30 14:51
@Aris_t2:

Following your instructions for using Firefox portable (above), when I start the .exe I am told another version of FF (my 132.0.2) is running.  I would think that--it being portable--it uses entirely different resources.    Why can the portable and "installed" version not run side by side?

**Comment by Aris-t2** [comment] 2024-11-30 15:05
The can, but this has to be setup.

You need a file `FirefoxPortable.ini` inside where FirefoxPortable.exe is.

Its content looks like:

```
[FirefoxPortable]
FirefoxDirectory=App\firefox
ProfileDirectory=Data\profile
SettingsDirectory=Data\settings
PluginsDirectory=Data\plugins
FirefoxExecutable=firefox.exe
AdditionalParameters=-purgecaches
LocalHomepage=
DisableSplashScreen=true
AllowMultipleInstances=true
DisableIntelligentStart=false
SkipCompregFix=false
RunLocally=false

# The above options are explained in the included readme.txt
# This INI file is an example only and is not used unless it is placed as described in the included readme.txt
```

**AllowMultipleInstances=true** has to be present.

**Comment by Nicholas-Steel** [comment] 2024-11-30 23:38
> Lets try a different approach.
> 
>     1. Download and setup [PortableFirefox](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%20133.0/FirefoxPortable_133.0_English.paf.exe/download).
> 
>     2. Start `FirefoxPortable.exe` and enable `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config`.
> 
>     3. Create `/chrome/` folder and extract [latest release (zip file) from here](https://github.com/Aris-t2/CustomCSSforFx/releases) to it.
>        ![image](https://private-user-images.githubusercontent.com/6013569/391225171-c047c936-d8f7-4b0c-b92d-9900344625be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTAxMDYsIm5iZiI6MTczMzAwOTgwNiwicGF0aCI6Ii82MDEzNTY5LzM5MTIyNTE3MS1jMDQ3YzkzNi1kOGY3LTRiMGMtYjkyZC05OTAwMzQ0NjI1YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMjMzNjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBkMTVjZWQwMmNjOTkxZWY5MzE1ZjM5YTAzMDQ5NjdiYjc2NGMyZjlkZTUwNWQwNmZjOGFhOTgxZGMwMWU5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ExQ2g6afwhCOgCJtlClLUD-qPUrI_ngaxLk4lrRVU8U)
> 
>     4. Start `FirefoxPortable.exe` , take and post a screenshot of the window showing this projects default setup (looks like this for me).
>        ![image](https://private-user-images.githubusercontent.com/6013569/391225326-013db4a2-21f5-4ee9-ab79-25af5a40c61d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTAxMDYsIm5iZiI6MTczMzAwOTgwNiwicGF0aCI6Ii82MDEzNTY5LzM5MTIyNTMyNi0wMTNkYjRhMi0yMWY1LTRlZTktYWI3OS0yNWFmNWE0MGM2MWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMjMzNjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODc3Y2U1YzJjMWZjZDYyMWUzYmZhNzc0MTJjOWQ1OWYxOTc1NjUyYzVhODJlMDYzN2JiMDhlYzNkYjkxOTY5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2Puc3sLbqjAv-xi74xar3I5p04nX-oDl-QlWN-t3S2c)
> 
>     5. Enable `tabs_below_navigation_toolbar_fx133.css`, restart Firefox and post a screenshot of the result (looks like this for me).
>        ![image](https://private-user-images.githubusercontent.com/6013569/391225356-ca363463-57ab-4aa9-a4a7-f420ca2d7231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTAxMDYsIm5iZiI6MTczMzAwOTgwNiwicGF0aCI6Ii82MDEzNTY5LzM5MTIyNTM1Ni1jYTM2MzQ2My01N2FiLTRhYTktYTRhNy1mNDIwY2EyZDcyMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMjMzNjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmYzNGZlNTYyYzY1ZjI1ODBhN2U1YjQyMzA0NWE5ZDAyYWYwZjY0ZWJmM2IxMGViOTk1ZWY5MDY2YjRhNGY0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XgKL6RNS4goE_bWfneXV63S0rIS1SI5eUzEXctfpc-A)
> 
> 
> This is were we would start troubeshooting.

> Lets try a different approach.
> 
>     1. Download and setup [PortableFirefox](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%20133.0/FirefoxPortable_133.0_English.paf.exe/download).
> 
>     2. Start `FirefoxPortable.exe` and enable `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config`.
> 
>     3. Create `/chrome/` folder and extract [latest release (zip file) from here](https://github.com/Aris-t2/CustomCSSforFx/releases) to it.
>        ![image](https://private-user-images.githubusercontent.com/6013569/391225171-c047c936-d8f7-4b0c-b92d-9900344625be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDg4MjgsIm5iZiI6MTczMzAwODUyOCwicGF0aCI6Ii82MDEzNTY5LzM5MTIyNTE3MS1jMDQ3YzkzNi1kOGY3LTRiMGMtYjkyZC05OTAwMzQ0NjI1YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMjMxNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDEyYzcxMjdhZWNkMWUxZTY5NGFiNTRiOGE2MzY3OGQ5ZmIwOTAyYWI1ZDJkN2EzZmU3ODM0OGIyMDBlOGQxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.A86AnASC8mKs3Z2kiGkEhzBNmvD48uG9C5ZwuDJdVwE)
> 
>     4. Start `FirefoxPortable.exe` , take and post a screenshot of the window showing this projects default setup (looks like this for me).
>        ![image](https://private-user-images.githubusercontent.com/6013569/391225326-013db4a2-21f5-4ee9-ab79-25af5a40c61d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDg4MjgsIm5iZiI6MTczMzAwODUyOCwicGF0aCI6Ii82MDEzNTY5LzM5MTIyNTMyNi0wMTNkYjRhMi0yMWY1LTRlZTktYWI3OS0yNWFmNWE0MGM2MWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMjMxNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGRlMzYyN2IwMDdiNmE2Nzk0MzlkNjE2ZDY1N2IwOTJiNzFjYWJhYzcyMWU2ZWM4ZDljZGQxODQyZGJjNDRiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Nen5z306Bbtr8oYHe0f-bv68ZwD9wTcFK2XyXmrpaL4)
> 
>     5. Enable `tabs_below_navigation_toolbar_fx133.css`, restart Firefox and post a screenshot of the result (looks like this for me).
>        ![image](https://private-user-images.githubusercontent.com/6013569/391225356-ca363463-57ab-4aa9-a4a7-f420ca2d7231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDg4MjgsIm5iZiI6MTczMzAwODUyOCwicGF0aCI6Ii82MDEzNTY5LzM5MTIyNTM1Ni1jYTM2MzQ2My01N2FiLTRhYTktYTRhNy1mNDIwY2EyZDcyMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMjMxNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjJiNTQ3ZGNhZmQzMmNjZTlhZTRjOGUyNzk0OTBjMmZmZWUyODUzZjYyMTgwYjI0MjkyNTBiYmUyNTA1NDM0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W82tH4z4QAqd32YT8-uUJqGN_GULkv2uNfLWwkrbCTU)
> 
> 
> This is were we would start troubeshooting.

1) I installed Firefox Portable (why does it have an installer? Doesn't that run counter to being portable?)

2) I copied the Chrome folder from my existing install of Firefox in to the Portable version's Profile and enabled `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config`.

3) I updated the the CSS folder with the copy from the newly released 4.6.4 package.

This is the result:
![image](https://github.com/user-attachments/assets/2c8c09f0-fc9a-4a43-9611-a3bda4f3e6e9)

If I copy my old copy of user.js it still looks correct.
If i copy my old copy of Prefs.Js however... things revert to the Tab Bar looking incorrect.

**Comment by Nicholas-Steel** [comment] 2024-12-01 00:07
> I think it could be profile related? I have the same problem but this won't occur if I use a fresh new profile
> 
> Here is what it should look like with Firefox 132 + CustomCSSforFx 4.5.4 : ![Firefox 132](https://private-user-images.githubusercontent.com/13227662/391232131-89e1bb57-7fe0-4023-bd6b-fe30dc6e52a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTE5MTAsIm5iZiI6MTczMzAxMTYxMCwicGF0aCI6Ii8xMzIyNzY2Mi8zOTEyMzIxMzEtODllMWJiNTctN2ZlMC00MDIzLWJkNmItZmUzMGRjNmU1MmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAwMDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZjBmMGUxY2QzYWYxNDI1ZGEzNTc3YmYxNjhiYjZiMjFkMmFlOTQ3ZDNiMTI0MmRlYzc4ZWQwOGE4YzM0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C_UXnAgHUVuEGlCl09Kcb99f7ghLbhvYFSWh298eXpw)
> 
> Here is what it looks with Firefox 132 + CustomCSSforFx 4.6.3 : ![Firefox 132 2](https://private-user-images.githubusercontent.com/13227662/391232144-ef192799-0c92-4987-8451-adcf0c2cc097.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTE5MTAsIm5iZiI6MTczMzAxMTYxMCwicGF0aCI6Ii8xMzIyNzY2Mi8zOTEyMzIxNDQtZWYxOTI3OTktMGM5Mi00OTg3LTg0NTEtYWRjZjBjMmNjMDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAwMDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMjBmYjNmZWZjZDA5YThiOWVkOGEyMThhMmFlOWJlZDI4OGQ2ZmNjMjUyOTdmYmFiMTQ2MzkyNTQ4OWVlMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nPlFUywwq00vwGJy1uU57JBCti790uuU_-fTHq2zcrs)
> 
> Here is what it looks with Firefox 133 + CustomCSSforFx 4.6.3 : ![Firefox 133](https://private-user-images.githubusercontent.com/13227662/391232154-d8acc531-bafd-42c8-8ff8-c9b166da62d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTE5MTAsIm5iZiI6MTczMzAxMTYxMCwicGF0aCI6Ii8xMzIyNzY2Mi8zOTEyMzIxNTQtZDhhY2M1MzEtYmFmZC00MmM4LThmZjgtYzliMTY2ZGE2MmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAwMDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YzcwZjA1OWM4NGNkNzMwNTZlMWQ4NDU1OTJjMzEwOTUzOTA3OWM4ZmVmN2RjM2ViYjI3NDA2ZGU0OTdlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O4TddNpHm7-ON0v-2SpzmOJRMt62rajRPSlP88DgzZE)
> 
> Here is what it looks with a fresh new profile (Firefox 133 + CustomCSSforFx 4.6.3) : ![Firefox 133 2](https://private-user-images.githubusercontent.com/13227662/391232161-b8564164-9e78-4dad-8a7f-cf32bfbb801f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTE5MTAsIm5iZiI6MTczMzAxMTYxMCwicGF0aCI6Ii8xMzIyNzY2Mi8zOTEyMzIxNjEtYjg1NjQxNjQtOWU3OC00ZGFkLThhN2YtY2YzMmJmYmI4MDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAwMDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxN2JiNTcyZjgzOWViNDdiZGUwYmViNzU0ZWM3YmFmZjA1YjYxOTA5MWI2Y2E3ZWFiYjVhMDljMTIyMDJhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UZ-vyIz6Pt3-ivYFTESFNwEAtMV2izvKZAznuNizqZQ)
> 
> As of the 4.6.3 CSS being used between Firefox 132 and 133, only `@import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/ /* for Firefox 132 and below */` and `@import "./css/tabs/tabs_below_navigation_toolbar_fx133.css"; /**/ /* for Firefox 133+ */` being altered
> 
> The address bar will go up there if I turned on `@import "./css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css"; /**/` on Firefox 133 but I guess that's off topic (Now I noticed I forgot to include the separate stop and reload buttons script but that should not really matter)
> 
> Windows 10 22H2 DPI: 96 (100%) default windows mode: dark default app mode: light Firefox theme: System Theme/Auto Windows system theme is Aero10 By vaporvance with DWMBlurGlass

Check if this exists in your Prefs.js file (in the root of the Profile folder)

`user_pref("layout.css.prefers-color-scheme.content-override", 0);`

Delete it if it does, **deleting this seems to resolve my issue.**

**Comment by Nicholas-Steel** [comment] 2024-12-01 00:16
Thank you Aris-t2 for your persistent support and suggestion of messing around with a portable install of Firefox, this made it easy to test changes and narrow down the cause.

Thank you MaxPSN, your examples of Firefox in various conditions reinforced the idea that the issue was related to something within the Profiles folder and that the issue wasn't external.

**Comment by jmcken1** [comment] 2024-12-01 04:17
Having the same problem with tab colors after updating to CSSforFx v4.6.4 on Firefox v133.0. I didn’t delete `layout.css.prefers-color-scheme.content-override` in Prefs.js, and instead found it in `about:config` and reverted it to its default (`2`), and I can confirm this fixes the tab colors. However, it also reverts Firefox’s own pages (settings, add-ons, etc.) from my preferred dark mode to light mode, so that’s not ideal.

**Comment by jmcken1** [comment] 2024-12-01 04:24
Slight update: So, that setting seems to be the same one as Settings → General → Website appearance. “Automatic” and “Light” work fine, but “Dark” breaks the tab colors. Is this a bug with CSSforFx or Firefox itself?

![image](https://github.com/user-attachments/assets/a69e3dec-23e8-4ee7-94dd-ba18ab15941e)
_Firefox v133.0 & CSSforFx v1.6.4 with “Dark” mode enabled (dark page background, broken tab colors)_

![image](https://github.com/user-attachments/assets/8fa1398c-8734-474d-886a-57d32d63889f)
_Firefox v133.0 & CSSforFx v1.6.4 with “Light” mode enabled (light page background, normal tab colors)_

**Comment by Aris-t2** [comment] 2024-12-01 14:40
> > Having the same problem with tab colors after updating to CSSforFx v4.6.4 on Firefox v133.0. I didn’t delete `layout.css.prefers-color-scheme.content-override` in Prefs.js, and instead found it in `about:config` and reverted it to its default (`2`), and I can confirm this fixes the tab colors. However, it also reverts Firefox’s own pages (settings, add-ons, etc.) from my preferred dark mode to light mode, so that’s not ideal.
> 
> So the root course should be the css reads the website appearance settings instead of the current browser theme That explains why the tab colors are correct if I switched to dark theme

You were right, I found the code causing this. The issue will be fixed on next update.

Classic squared tabs had a wrong @media rule, that looked for the website related pref too.

**Comment by Nicholas-Steel** [comment] 2024-12-02 01:03
So with all this sorted, my original assumption of only needing to update the CSS folder is back to being correct.

**Closed** 2024-12-02 05:10 UTC
Labels: BUG, fixed
