### ISSUE TITLE
[macOS] Blank status bar and theme not visible

### ISSUE THREAD

**Issue by fbnk** [Aris-t2/CustomCSSforFx#345] opened 2021-05-18 20:28 UTC
Since one of the recent Firefox updates for macOS, the status bar is blank. This was a problem before and seems to be there again. Is this something I can adjust in the userChrome.css file or does it need to be done somewhere else? 
I'm using the latest version of CustomCSSforFx

<img width="1047" alt="Bildschirmfoto 2021-05-18 um 22 19 12" src="https://user-images.githubusercontent.com/13615809/118719026-3c9c2200-b828-11eb-9029-df87af29126f.png">

**Comment by 2BeeOrNot** [comment] 2021-05-18 22:29
Application Menu -> Customize Toolbar...
Check Title Bar bottom left corner.

**Comment by fbnk** [comment] 2021-05-19 06:35
@2BeeOrNot I'm sorry, but where can I find that menu? I can't find a menu entry that says "customize toolbar" in the Firefox settings.

**Comment by 2BeeOrNot** [comment] 2021-05-19 16:21
In the "hamburger" menu. Maybe you have it hidden. You can also right click in an empty area of the tab bar area.
![burger](https://user-images.githubusercontent.com/63317977/118847846-2a5bcb80-b89c-11eb-9178-4cd09d83eb07.jpg)
![Burger2](https://user-images.githubusercontent.com/63317977/118848107-7149c100-b89c-11eb-878d-eebc6c2c03f5.jpg)
![Burger3](https://user-images.githubusercontent.com/63317977/118848443-c08ff180-b89c-11eb-97ce-d7de9570653c.jpg)

**Comment by fbnk** [comment] 2021-05-19 16:27
Thank you! Unfortunately it's already unchecked, so it doesn't make any difference. I guess CustomCSSforFx needs an update. Like I said, I guess it has been like this before.

**Comment by 2BeeOrNot** [comment] 2021-05-19 17:19
It needs to be checked, not unchecked. You are looking to get the tab title displayed in the title bar like this?

![burger5](https://user-images.githubusercontent.com/63317977/118855087-6ba3a980-b8a3-11eb-902b-385533663ce2.jpg)

Maybe I don't understand what you are looking for. The area you outlined in your first post is the title bar, not the status bar.

**Comment by fbnk** [comment] 2021-05-19 18:05
Of course, it's the title bar. It should look like it did before: 
<img width="1047" alt="Bildschirmfoto 2021-05-18 um 22 19 12" src="https://user-images.githubusercontent.com/13615809/118862077-88f56980-b8dd-11eb-8721-67d5f91301b7.png">

Currently there is a gray bar, which came with one of the last FF updates.

**Comment by 2BeeOrNot** [comment] 2021-05-19 23:23
I misunderstood your issue. I didn't know you could have the theme extend into the title bar.

**Comment by Aris-t2** [comment] 2021-05-22 09:22
I could reproduce the issue. It was caused by "tabs not on top" mode using lw themes.
Because of recent changes the theming code was not applied to titlebar.

Check v3.2.0 pre5 on release page. It should take care of the issue.

Make sure you are using "tabs_below_navigation_toolbar_fx89_macOS.css".

**Comment by fbnk** [comment] 2021-05-22 19:59
Unfortunately it didn't work. The only thing changed is, that the three dots slightly moved a bit upwards.
I tried both setting - of course one at a time - but it didn't work out:
```
@import "./css/tabs/tabs_below_navigation_toolbar_fx89_macOS.css"; /**/
@import "./css/tabs/tabs_below_navigation_toolbar_fx89_macOS_default_tabs.css"; /**/
```

<img width="1440" alt="Bildschirmfoto 2021-05-22 um 21 54 51" src="https://user-images.githubusercontent.com/13615809/119239304-80ed3200-bb48-11eb-981d-a0eae55f1ee2.png">

**Comment by Aris-t2** [comment] 2021-05-25 15:33
Not sure why it does not work for you. For me "lw themes" now also target Firefox titlebar.

**Comment by fbnk** [comment] 2021-05-25 19:41
I tried your latest version (pre6),and the only thing changed is that the space of the titlebar lost a bit hight. 
<img width="1439" alt="Bildschirmfoto 2021-05-25 um 21 36 39" src="https://user-images.githubusercontent.com/13615809/119558421-a9bc3400-bda1-11eb-98fa-9154abfba5bb.png">

I also tried another theme, and one of the default FF themes  (Alpenglow) seem to work, but it's the only one. The other (default) themes all have just a gray stripe as the titlebar.
<img width="1440" alt="Bildschirmfoto 2021-05-25 um 21 36 56" src="https://user-images.githubusercontent.com/13615809/119558437-af197e80-bda1-11eb-878d-598d545bfbd3.png">

**Comment by Aris-t2** [comment] 2021-06-06 15:37
Looks like there was an order issue in my latest code, try this in userChrome.css/my_userChrome.css:

```css
#titlebar:-moz-lwtheme {
  background-image: var(--lwt-header-image, var(--lwt-additional-images)) !important;
}
```

**Comment by Aris-t2** [comment] 2021-06-06 15:40
Test this: [chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/6604433/chrome.zip)

**Comment by fbnk** [comment] 2021-06-12 08:25
Sorry for the late feedback. I tried the new version and it looks quite good. The appearance at the top in the title bar is just a little bit shifted. Below two screenshots one with and one without CustomCSS.
<img width="1440" alt="Bildschirmfoto 2021-06-12 um 10 05 37" src="https://user-images.githubusercontent.com/13615809/121770232-75e65a00-cb68-11eb-9b2d-3544e77798f3.png">
<img width="1440" alt="Bildschirmfoto 2021-06-12 um 10 02 55" src="https://user-images.githubusercontent.com/13615809/121770234-7a127780-cb68-11eb-90b2-8d61e1b5d26f.png">

**Comment by Aris-t2** [comment] 2021-06-14 16:10
The top toolbars image used by the theme is applied to all top toolbars except titlebar. Adding the image manually to the titlebar causes it not being correctly align. Nothing I can do about.

**Comment by Aris-t2** [comment] 2021-07-20 16:25
I think we can close this one now.

**Closed by Aris-t2** 2021-07-20 16:25 UTC
Labels: BUG, fixed
