### ISSUE TITLE
[Fx71] tab_close_on_active_tab_only displays close icons on all tabs, not just the active one. 

### ISSUE THREAD

**Issue by jrowat** [Aris-t2/CustomCSSforFx#254] opened 2019-12-06 14:04 UTC
1. Describe the issue
With FF71, tab_close_on_active_tab_only does not cause the close button to appear only on the active tab.  Instead, the close button appears on every tab.
Disabling that option and enabling other tab close icon options works - "show on hover only" works fine, 

2. What should have happened instead?
The Close Tab button should only appear on the active tab.

3. Steps to reproduce the issue?
Install FF71.  Pull down a fresh copy of CustomCSSforFX and install it in the profile/chrome folder.  uncomment the @import "./css/tabs/tab_close_on_active_tab_only.css"; /**/  line.
Start firefox and open multiple tabs.  Observe:  Every tab has a "close tab" button.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
With:
![image](https://user-images.githubusercontent.com/47221310/70327933-e428be80-1805-11ea-9ea6-b77e3829379b.png)

Without:
![image](https://user-images.githubusercontent.com/47221310/70328070-2eaa3b00-1806-11ea-9833-d7e147719b59.png)

5. System information
- OS & OS version:   Windows 10 Pro 1909
- OS theme name:  I have no idea.  It's Win10, "default"?
- DPI / HiDPI resolution: Happens in both 1920x1080 and 4K
- Firefox version: 71.0 64-bit default release.
- Firefox theme / lw-theme: Mozilla default
- This projects settings the issue occurs with: 

I have enabled:
```
@import "./config/general_variables.css"; /**/
@import "./css/buttons/icons_colorized.css"; /**/
@import "./css/buttons/whatnew_button_always_hidden.css"; /**/
@import "./css/appbutton/appbutton_popup_more_icons.css"; /**/
@import "./css/appbutton/appbutton_popup_icons_colorized.css"; /**/
@import "./css/tabs/tabs_below_navigation_toolbar_fx72.css"; /**/
@import "./css/tabs/tabs_multiple_lines_fx71_force_newtab_button_visibility.css"; /**/  /* Fx 71+ */
@import "./css/tabs/missing_tab_favicon_restored_default.css"; /**/
@import "./css/tabs/tab_close_on_active_tab_only.css"; /**/
@import "./css/generalui/private_mode_indicator_hidden.css"; /**/
@import "./css/generalui/bookmark_icons_colorized.css"; /**/
@import "./css/generalui/context_bfrsb_labels_without_icons.css"; /**/
@import "./css/generalui/searchbar_glassplus_indicator_hidden.css"; /**/
@import "./css/toolbars/general_toolbar_colors.css"; /**/
@import "./css/locationbar/locationbar_adjustments.css"; /**/
@import "./css/locationbar/compact_mode_reduce_fontsize.css"; /**/
@import "./css/locationbar/identitybox_colors.css"; /**/
@import "./css/locationbar/icons_colorized.css"; /**/
@import "./css/locationbar/pageaction_separator_in_location_bar_hidden.css"; /**/
@import "./css/locationbar/starbutton_is_last_pageaction_button.css"; /**/
@import "./css/locationbar/starbutton_popup_preview_image_hidden.css"; /**/
@import "./css/locationbar/dropmarker_at_the_end.css"; /**/
@import "./css/locationbar/dropmarker_visible.css"; /**/
@import "./css/locationbar/ac_popup_url_and_title_50percent_width.css"; /**/
@import "./css/locationbar/ac_popup_result_font_size.css"; /**/
@import "./my_userChrome.css"; /**/

```
All other lines are disabled.  I have not customised the other CSS files.  I do not have a my_userchrome.css file.

**Comment by Aris-t2** [comment] 2019-12-06 18:34
The issue is caused by multiple tab lines option. This will be fixed on next update.

Use this workaround till then.
```css
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab:not([pinned]):not([selected="true"]) .tab-close-button,
#TabsToolbar #tabbrowser-tabs .tabbrowser-tab[pinned]:not([selected="true"]) .tab-close-button {
  visibility: collapse !important;
  display: none !important;
}
```

**Closed** 2019-12-14 15:29 UTC
Labels: WORKAROUND, fixed
