### ISSUE TITLE
[C][Win][Fx58] - tabthrobber_fx56 problem

### ISSUE THREAD

**Issue by Pizzapops** [Aris-t2/CustomCSSforFx#16] opened 2017-10-25 19:17 UTC
![aris-58-throbber](https://user-images.githubusercontent.com/33039961/32018248-e9882636-b98e-11e7-8ac3-edeb49171ee9.jpg)

The tabthrobber leaves a remnant of the loading.png on screen. It is about 6px higher and 6px to the right of proper location. If I delete both ".**tab-loading-burst[bursting]::before**" lines, the throbber works. Starting Fx58 with no addons gives the same results. 

Win 10, Fx58-10/25, std light theme

**Comment by Aris-t2** [comment] 2017-10-25 21:06
This will be fixed on next build.

Looks like the latest Fx57 beta and Fx58 Nightly builds changed something, that was not present when this feature was added.

**Comment by Aris-t2** [comment] 2017-10-27 08:56
Can you confirm the issue is fixed for you too?

**Comment by Pizzapops** [comment] 2017-10-27 13:15
You have fixed the problem. Thanks

**Closed** 2017-10-27 13:46 UTC
