### ISSUE TITLE
Large space to left of icons in menu bar

### ISSUE THREAD

**Issue by mwrubin** [Aris-t2/CustomCSSforFx#566] opened 2023-02-28 19:43 UTC
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so the issue report is most likely wrong here.
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Just upgraded to Firefox 110.0.1. A large blank space has appeared to the left of the icons on the menu bar. Takes up 40% of the menu bar.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes

4. Screenshots showing the issue (drag & drop images into this post):

![image](https://user-images.githubusercontent.com/47424415/221960709-df12ada5-11aa-43e1-9e49-6c49d4fdf086.png)

5. System information
- OS & OS version: Windows 11
- DPI / HiDPI (e.g. 100%, 125%...): 150%
- Firefox version: 110.0.1
- Firefox theme (e.g. default, build in light/dark, external theme + link): 
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): Yes

**Comment by Maryse47** [comment] 2023-03-01 16:19
I hit the exact same issue after upgrading to 110.0.1. Release notes is [here](https://www.mozilla.org/en-US/firefox/110.0.1/releasenotes/)

**Comment by Maryse47** [comment] 2023-03-01 16:22
I can temporarily fix this by moving some items to the bookmarks bar back and forth but it re-appears after browser restart.

**Comment by Aris-t2** [comment] 2023-03-01 16:47
I tried to replicate this issue in Firefox 110.0.1 and Firefox 112 Nightly, but was no able to get the same result as you.

Could you replace your files inside chrome folder with latest release/dev build and repeat everything you set in userChrome.css.

How does the window look without any code inside chrome folder?

![image](https://user-images.githubusercontent.com/6013569/222205900-39adbac7-32ac-4f21-b141-64da2e1cecc3.png)
![image](https://user-images.githubusercontent.com/6013569/222205957-d6be4290-efb6-4a63-86cb-f8fe9aa87a40.png)

**Comment by Maryse47** [comment] 2023-03-01 17:26
I was able to reproduce this even with _chrome_ folder empty so this may be not related to this project in the end.

For me the permanent fix was to move the _Bookmarks toolbars item_ element at the far left of the bar (where this empty space is). I had to do it in 2 steps since at first moving it the the far left resulted in appearing it in far right. In the end this seems to block this _black hole on the left_ problem. Someone should report regression to mozilla.

**Comment by mwrubin** [comment] 2023-03-01 17:38
Yes, this is what it looks like with no code in the userchrome.css file. Same problem.
![image](https://user-images.githubusercontent.com/47424415/222218306-93d89f41-d2dc-4a68-83b4-f06707cdbe90.png)

Is there a tweak to the css code that could fix it?

**Comment by mwrubin** [comment] 2023-03-01 17:59
I've also replaced everything in my chrome folder with the latest build and applied everything I had set in userchrome.css.  Same result.  
![image](https://user-images.githubusercontent.com/47424415/222223211-f8882bc3-5a60-4cff-8b33-859edcd0f4fe.png)

**Comment by Aris-t2** [comment] 2023-03-01 18:57
Open customizing mode and look, if a flexible space was added to the menubar. Remove it, if it is present.

![image](https://user-images.githubusercontent.com/6013569/222237706-de4ed0a5-a770-4c10-9d4d-1862b984043c.png)

**Comment by mwrubin** [comment] 2023-03-01 20:20
No there's no flexible space added anywhere.

**Comment by Maryse47** [comment] 2023-03-02 22:49
This is now reported as regression to mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1819980

Someone on [reddit](https://old.reddit.com/r/firefox/comments/11g98xd/latest_firefox_update_broke_toolbar_elements/janlpdf/) proposed temporary css workaround (I didn't test it):

```
#PersonalToolbar[collapsed=false] > #personal-toolbar-empty[nowidth] > #personal-toolbar-empty-description {
    width: 0 !important; /** restore rule modified in Firefox 110.0.1 by bug 1812636 **/
}
```

I thin this can be closed here as this isn't related to the project unless you want to implement above workaround in it.

**Comment by mwrubin** [comment] 2023-03-03 03:33
That fixed it.  Thanks for finding that.

**Comment by Aris-t2** [comment] 2023-03-03 07:23
@Maryse47 
Thanks for pointing this out.

**Closed** 2023-03-11 14:09 UTC
Labels: Firefox bug
