### ISSUE TITLE
Issues with default_tabs_photon.css

### ISSUE THREAD

**Issue by jmuchemb** [Aris-t2/CustomCSSforFx#552] opened 2023-01-29 02:56 UTC
I prefer the photon tabs because they're compact, clear and elegant, which is why I'm still using FF78esr. Thanks to this project, I'm close to get back the photon UI in FF109, but I have a few  issues:

1. unwanted "holes" & bottom border on selected tab:

- expected (FF78):
![ff78](https://user-images.githubusercontent.com/11165223/215300896-90b842bb-f2c0-4e31-a98e-e7074b1a6dba.png)
- actual (FF109):
![ff109](https://user-images.githubusercontent.com/11165223/215300900-aa35abfe-95ab-4108-b1aa-9b99bfc2a972.png)
- zoom on the issue, bad pixels in red:
![ff109_highlight](https://user-images.githubusercontent.com/11165223/215301491-566609b9-e051-4b36-be8b-f9267fa42b79.png)

2. tabs bar is 1px higher

See screenshots above. Not sure if it has any relation with my scale settings (see conf at the end). Currently, I can fix with:
```css
:root {
  --tab-min-height: 28px !important;
}
```

3. much less important because I almost never multiselect but for consistency I have a preference for the old rendering (photon is about true tabs whereas in the new UI, tabs are buttons):

- expected (FF78):
![ff78_multiselect](https://user-images.githubusercontent.com/11165223/215300975-0f0205d8-0da7-4961-a8f8-f3cb1007064d.png)
- actual (FF109):
![ff109_multiselect](https://user-images.githubusercontent.com/11165223/215300982-13b2cd5a-2607-490e-892b-2fc761702dc8.png)

---
- Linux X11 158dpi
- default theme
- notable prefs for FF78:
```js
user_pref("layout.css.devPixelsPerPx", "1");
```
- notable prefs for FF109:
```js
user_pref("ui.textScaleFactor", 100);
```
- enabled customcssforfx 4.3.0 for FF109:
```
appbutton/appbutton_popup_icons.css
appbutton/appbutton_popup_icons_colorized.css
buttons/buttons_on_navbar_more_compact_mode.css
locationbar/megabar_disable_openviewonfocus.css
locationbar/megabar_expanding_breakout_disabled.css
locationbar/ac_popup_megabar_compact_results.css
tabs/default_tabs_photon.css
tabs/tabs_below_navigation_toolbar.css
toolbars/general_toolbar_colors.css
```

**Comment by Aris-t2** [comment] 2023-01-29 16:48
Test latest v3 release: https://github.com/Aris-t2/CustomCSSforFx/releases/

It should fix the mentioned issues or at least improve the situation. Some rules are not supported by current Firefox anymore, so separators code had to be adopted to what is possible at the moment.

**Comment by jmuchemb** [comment] 2023-01-29 17:47
Sorry, I don't understand. As I wrote (« enabled customcssforfx 4.3.0 for FF109 »), this issue was open for the latest v3 release.

**Comment by Aris-t2** [comment] 2023-01-29 17:49
I uploaded [custom_css_for_fx_v4.3.0v3.zip](https://github.com/Aris-t2/CustomCSSforFx/releases/download/4.3.0/custom_css_for_fx_v4.3.0v3.zip) an hour ago.

**Comment by jmuchemb** [comment] 2023-01-29 18:13
(Oh, I didn't know that files could be added like that to a release.)

So there would be no way to fix the biggest issue, i.e. to remove the bottom border of the selected tabs ? Hmm, I realize that this issue happens only when tabs are below navigation bar. The « bottom border » I'm talking about may be the top border of the main content: I wonder if this top border can be removed, and tab bar be in charge of drawing this border for unselected tabs.

**Comment by Aris-t2** [comment] 2023-01-29 19:22
Does this help?

```css
#navigator-toolbox {
  border-bottom: 0 !important;
}
```

**Comment by jmuchemb** [comment] 2023-01-29 21:02
Maybe.
![ff109v3a'](https://user-images.githubusercontent.com/11165223/215355295-14cad877-f4f5-48be-9649-dae731596ba0.png)

Then, I hacked something by adding:
```css
.tabbrowser-tab:not([visuallyselected]) {
  border-bottom: 1px solid #bcbebf !important;
}
```
![ff109v3c'](https://user-images.githubusercontent.com/11165223/215355333-15843f69-0667-4509-9e61-7eb705170389.png)

What is also great is that the border is now 1px above, which fixes issue 2.

But I don't know if the border can be extended where there is no tab.

**Comment by Aris-t2** [comment] 2023-01-30 06:32
Either the bottom toolbar (#TabsToolbar), the tab box (#tabbrowser-tabs) or the whole toolbox (#navigator-toolbox) have to set the color of the line there.
This will also affect the active tab.

**Comment by jmuchemb** [comment] 2023-01-31 09:53
So nothing that covers only the part at the right of tabs, which means that removing the bottom border is a wrong approach.

I should have read the README earlier: I didn't know it was so easy so inspect chrome elements. I found something that fixes issue 1 completely:
```css
.toolbar-items {
  margin-bottom: -1px;
}
```
![ff109a](https://user-images.githubusercontent.com/11165223/215699067-17021f18-3ce4-470c-8ab8-9c7165623638.png)

This also move tabs 1px below, which is a little closer to FF78 so no need to compensate that. On the other side, issue 2 still needs to be fixed: `--tab-min-height: 28px` does the job but no idea if it's the cleanest way to change default_tabs_photon.css

At last, maybe we should drop all your changes in 4.3.0v3
- I looks like you soften the sides of the selected tab to make the holes in issue 1 less visible. But with the above fix, that does the contrary so I'd revert. We could even remove the shadow completely.
- Making multiselect like FF78 is more complicated than I expected, and if it's not exactly the same I'm not sure to prefer over the current 4.3.0. There also a hover effect on `[multiselected]:not([selected])` tabs. For the record:
![ff78_multiselect](https://user-images.githubusercontent.com/11165223/215724805-65d9cfb3-90f4-455e-9246-3e353404970a.png)

**Comment by Aris-t2** [comment] 2023-01-31 17:47
There is always room for improvement, but options have to keep compatibility when used with other options, so some changes are for individual configurations only.

Moving tab toolbars content by one pixel creates a line above tabs (visible on your screenshot). Try something like this:

```css
#TabsToolbar #tabbrowser-arrowscrollbox {
  margin-top: 1px !important;
  margin-bottom: -1px !important;
}
```

When using lw-themes active tab still overlaps with the line, because tabs become (semi)transparent.

Changing tab height to 28px sounds like a good idea.

> maybe we should drop all your changes in 4.3.0v3

Some changes were required after Mozilla dropped support for a few rules used in that file. Softening the borders was not my intention. This will be improved.
Also multiselect will receive an update, but replicating Fx78 ui is not the main goal here.

The hover effect is not part of browsers default code, I will change it to this:
![image](https://user-images.githubusercontent.com/6013569/215841379-0f84ffea-3025-4456-b243-26dddbbbb2a0.png)

**Comment by jmuchemb** [comment] 2023-01-31 19:59
> Moving tab toolbars content by one pixel creates a line above tabs (visible on your screenshot).

Oops.

> Try something like this:
> 
> ```css
> #TabsToolbar #tabbrowser-arrowscrollbox {
>   margin-top: 1px !important;
>   margin-bottom: -1px !important;
> }
> ```

Thanks! It works.

> When using lw-themes active tab still overlaps with the line, because tabs become (semi)transparent.

Even if I have some knowledge of CSS, there are use cases like themes that I don't know so it's hard for me to contribute something ready to merge.

> but replicating Fx78 ui is not the main goal here.

Just in case, I repost a screenshot of FF78 multiselect without userChrome.css:
![ff78a](https://user-images.githubusercontent.com/11165223/215866114-40799696-9a9d-428b-928d-0ec6d10b4042.png)

> The hover effect is not part of browsers default code,

(I don't understand: FF78 does have a hover effect on the blue line and I'd be surprised we could not replicate that in recent FF with some :hover line.)

> I will change it to this: ![image](https://user-images.githubusercontent.com/6013569/215841379-0f84ffea-3025-4456-b243-26dddbbbb2a0.png)

Your first tab is strange. Not even a bottom border. What's its state?

But the 2nd & 3rd tabs look great.

**Comment by Aris-t2** [comment] 2023-02-01 09:27
> (I don't understand: FF78 does have a hover effect on the blue line and I'd be surprised we could not replicate that in recent FF with some :hover line.)

I meant the hover effect for multiselected tabs is not part of default tabs / tabs code anymore in current Firefox versions.

The change currently in v4.3.1 adds a hover effect to actually hovered multiselected tabs. Not sure why non-hovered multiselected tabs offer hovered effect too in Fx78.

> Your first tab is strange. Not even a bottom border. What's its state?

`multiselected & not hovered` | `multiselected & hovered` | `selected & not hovered`
(tabs are no top in that screenshot, so no line issues below tabs)

**Comment by ImSpecial** [comment] 2023-02-02 22:03
I have no idea what you did since 4.2.9, but since updating this morning to 4.3.1v2, my tabs are F*****....

![Animation123](https://user-images.githubusercontent.com/4022372/216458814-34676f4f-d743-4233-8853-09951f43fc74.gif)

I tried 4.3.0v5 and same thing, I then went back to the last good version that I was using before all this "4.2.9" and things are behaving correctly again.

What happens in the gif is when you have pinned tabs (one or more) and lots of tabs opens, so they overflow off the edge, that glitch starts to happen until you don't have so many tabs open.

(Also, sorry for the hijack, it seemed relevant here to post, I can make a new post if you want.)

**Comment by Aris-t2** [comment] 2023-02-03 10:25
[4.3.1v3](https://github.com/Aris-t2/CustomCSSforFx/releases/) fixes dancing photon tabs ;-)

**Comment by jmuchemb** [comment] 2023-02-04 04:24
About the bottom line of tabs, I'd sum up what I prefer as follows: regardless the position of tabs, all tabs except the `selected` one should have one.

(In my FF78 screenshots with bottom tabs, there's no bottom line for the multiselected tabs, but that's actually not the most logical.)

I've just had time to try changes since my last comment:
![ff109_4 3 1v3_top](https://user-images.githubusercontent.com/11165223/216746253-1fc05d4d-cef9-4e21-a641-885918dcbbba.png)
![ff109_4 3 1v3_bottom](https://user-images.githubusercontent.com/11165223/216746251-0b611c01-7a8d-43a1-890e-49d1ba9a209e.png)

1. About below tabs, I thought we found a way to not have a bottom line for the selected tab. Any plan to include this change?
2. `multiselected & not hovered` tab on top (but maybe also on the bottom if the previous point is done) doen't have a bottom line and as I wrote at the beginning, I find this strange
3. For tabs on top (only a suggestion because I don't use this settings), an height of 1px for the top blue line is hardly 
visible.

**Comment by Aris-t2** [comment] 2023-02-04 10:18
1. This change must be part of `tabs below navigation toolbar`, so it will affect alle tab options.
2. I think I know now why Fx78 photon tabs used a "hovered" color effect on multiselected tabs. That bottom border is probably one of the reasons.
3. I will restore the 2px line an add a color mix rule. The result will get closer to Fx78 tabs ui.

![image](https://user-images.githubusercontent.com/6013569/216761219-b97e2a8c-e093-41ad-97ab-60971ba413a4.png)
selected | multiselected | multiselected & hovered | default | multiselected

**Comment by ImSpecial** [comment] 2023-02-04 20:11
I hope whatever you're doing you make this all optional or a specific fix for OP, because your ruining the tabs for others here...

First, v4 does not fix the "dancing" tab problems introduced, and since moving past "4.2.9" the borders and lines on the tabs now look absolute shit atm, I'm way to time limited to figure this out, so I'm just staying on "4.2.9" until Firefox breaks things again, but some pictures to leave you with. (FF 109.0.1 | 4.3.1v4 vs. 4.2.9)


new:
https://i.imgur.com/g5a4z9i.png

old:
https://i.imgur.com/YP6tS8N.png

--

new:
https://i.imgur.com/9J3iyZR.png

old:
https://i.imgur.com/HzndsxD.png

--

new:
https://i.imgur.com/e9ULfPL.png
https://i.imgur.com/JPxuyYN.png

old:
https://i.imgur.com/21H6XLS.png
https://i.imgur.com/UInlQGm.png

**Comment by Aris-t2** [comment] 2023-02-05 10:57
This is still WIP.

I could reproduce the dancing tabs before, but they are gone for me after 4.3.1v4 changes. I think this needs more testing.

Changes are required, because Mozilla removed a few rules used by tab separators.

I tried to improve things again with 4.3.1v5.

**Comment by Aris-t2** [comment] 2023-02-05 11:10
Current status of "photon tabs" (4.3.1v5):
- rewritten tab separators code (because Mozilla removed some rules)
- added code for "multiselected" tabs (lighter top line, darker background)
- tested [code to move tabs 1px vertically](https://github.com/Aris-t2/CustomCSSforFx/issues/552#issuecomment-1410813138) inside "tabs not on top file", but it caused issues in some cases (removed in 4.3.1v5)
- [dancing tabs](https://github.com/Aris-t2/CustomCSSforFx/issues/552#issuecomment-1414435283), if tabs are pinned (This happens in some cases only? Needs more testing)

**Comment by Aris-t2** [comment] 2023-02-05 11:16
@ImSpecial 
Test [4.3.1v5](https://github.com/Aris-t2/CustomCSSforFx/releases/) and upload your zipped `chrome `folder here, if the issue still exists.

**Comment by ImSpecial** [comment] 2023-02-05 19:30
v5 does seem to fix up all issues I've had previously, which is great! It might even be better in fact.

I did notice that there is a missing tab separator when moving/dragging tabs around with the new 4.3.1v5 version.

Old:
![old good](https://user-images.githubusercontent.com/4022372/216840383-1348e3ff-6ad4-4e17-9e35-2589bcd62f7a.png)
New:
![new missing](https://user-images.githubusercontent.com/4022372/216840390-66c4a73e-d29b-489c-ac00-b6b54920f584.png)

Other then that, seems really good.

**Comment by Aris-t2** [comment] 2023-02-06 12:32
I think we can restore the one marked in your screenshot.

**Comment by ImSpecial** [comment] 2023-02-06 21:45
I don't have time to take screenshots nor gifs, but I would suggest looking under a microscope at the tab bar with and without the "Open a new Tab (Crtl+T)" button pinned to it. I noticed shifting tab text when moving them, and the highlight color at the top of the tabs were inconstant while moving them as well, all with the button pinned, things looks fine otherwise without the button there.

**Comment by jmuchemb** [comment] 2023-02-06 22:10
Here is an issue with pinned tabs when some tabs are hidden (scrolling enabled) (4.3.1v6) (is it the first issue ImSpecial is talking about ?):

- FF109 with scrolling:
![ff109_pinned_scroll](https://user-images.githubusercontent.com/11165223/217098558-e9672e0f-120c-4b64-a938-da694220f585.png)
- FF109 without scrolling:
![ff109_pinned](https://user-images.githubusercontent.com/11165223/217098561-c27b5018-3e95-43a1-9b78-955a42b4f6fb.png)
- FF78 with scrolling:
![ff78_pinned_scroll](https://user-images.githubusercontent.com/11165223/217098551-40eab546-9c3c-469e-828d-469f31baf446.png)

Also the lack of separator between pinned tabs, in comparison to FF78.

> EDIT: I'm also not a fan of the thin border line that's around the selected/highlited tab, I'd rather have no line like in 4.2.9

What do you mean ?

**Comment by jmuchemb** [comment] 2023-02-06 22:21
>> 1. About below tabs, I thought we found a way to not have a bottom line for the selected tab. Any plan to include this change?
>
> 1. This change must be part of `tabs below navigation toolbar`, so it will affect all other tab options too.

The issue is still there; did you mean that _it would all other tab options too, which would be wrong_ ?

If the CSS is too limited to have such kind of conditional rules, what about a new file e.g. `default_tabs_photon_below_navigation_toolbar.css` ? I would contain something like:
```css
@import "default_tabs_photon.css";
@import "tabs_below_navigation_toolbar.css";

#TabsToolbar #tabbrowser-arrowscrollbox {
  margin-top: 1px !important;
  margin-bottom: -1px !important;
}
```

**Comment by Aris-t2** [comment] 2023-02-07 09:51
@ImSpecial 
Tab text shifting glitch occurs for me even with default tabs. Not sure what exactly causes this, but mostly noticeable is the initial tab to the left of the one we moved.

The thin "borders" of active tabs can be hidden or at least their opacity can be reduced for lw-themes. Borders will still be part of the default non-themed active tab like on older Fx versions.

@jmuchemb 
I'll try to improve the pinned tab for overflow mode, but restoring tab separators for pinned tabs breaks the ui, because of how Firefox moves pinned tabs in overflow mode. So no separators there for now.

> The issue is still there; did you mean that it would all other tab options too, which would be wrong ?

I meant default tabs and classic squared tabs would be affected by a change in tabs_below_navigation_toolbar.css too. In fact the code might do a good job in some cases, but breaks things in other cases incl. photon tabs. See the screenshots posted by [ImSpecial](https://github.com/Aris-t2/CustomCSSforFx/issues/552#issuecomment-1416840247).
Therefore it should not be part of any option atm, but everybody, who can improve the own config with it, is free to use it.

Please test [4.3.1v7](https://github.com/Aris-t2/CustomCSSforFx/releases)

**Comment by jmuchemb** [comment] 2023-02-07 19:18
> > The issue is still there; did you mean that it would all other tab options too, which would be wrong ?
> 
> I meant default tabs and classic squared tabs would be affected by a change in tabs_below_navigation_toolbar.css too. In fact the code might do a good job in some cases, but breaks things in other cases incl. photon tabs. See the screenshots posted by [ImSpecial](https://github.com/Aris-t2/CustomCSSforFx/issues/552#issuecomment-1416840247). Therefore it should not be part of any option atm, but everybody, who can improve the own config with it, is free to use it.

Oh, I didn't test all releases and didn't notice that v4 included it. 

> Please test [4.3.1v7](https://github.com/Aris-t2/CustomCSSforFx/releases)

For your information, selected/multiselected pinned tabs in overflow mode have a grey line above the blue line. I don't think I'll notice it over time.

Thank you a lot for all your work. Since it's been a while I haven't upgraded my Debian unstable, I don't know when I'll find time to switch to FF109. It's easier for me to upgrade to 102 first and I'll probably do that this week, now that I know how to fix the biggest issues in the meantime :)

**Comment by Hobbix** [comment] 2023-02-15 04:19
The separators for pinned inactive tabs are placed incorrectly.
1. There should be no separator before the first tab pinned.
2. There is no separator between the last pinned tab and the normally inactive tab.

![11](https://user-images.githubusercontent.com/8199105/218927402-0e27b184-f983-43af-986d-ad14e54337e8.png)

It should be like this:

![22](https://user-images.githubusercontent.com/8199105/218927492-eb63377b-227b-480b-8e1e-65b74976431d.png)

**Comment by Aris-t2** [comment] 2023-02-15 13:45
There are no separators in [4.3.1v7](https://github.com/Aris-t2/CustomCSSforFx/releases) for pinned tabs. They won't be restored.

**Comment by Hobbix** [comment] 2023-02-18 22:18
No separator between last pinned tab and first inactive regular (unpinned) tab.


> There are no separators in [4.3.1v7](https://github.com/Aris-t2/CustomCSSforFx/releases) for pinned tabs. They won't be restored.

Why did you decide to remove the separators between the pinned tabs? It is technically possible to make them there so far.

**Comment by Aris-t2** [comment] 2023-02-22 07:55
@ArtyoZ 
Open a new issue, post a screenshot and the options you are using (fill the template with info ;-)).

@Hobbix 
Separators code had to be rewritten to compensate rules deprecated by Mozilla (e.g. [beforeselected-visible], [beforehovered]). That change causes pinned tabs to break the ui.
If you can offer code, that catches all cases without breaking tabs or pinned tabs, I will look into it.

- separators before and after non-selected/non-multiselected tabs
- separator before first tabs (non-selected/non-multiselected)
- separator after last tab (non-selected/non-multiselected)
- separator after selected/multiselected tab(s) after starting moving them
- probably other cases I did not take care of yet

**Comment by ArtyoZ** [comment] 2023-02-24 22:31
> @ArtyoZ Open a new issue, post a screenshot and the options you are using (fill the template with info ;-)).
> 
> Edit: Change this
> 
> ```css
> @media (-moz-platform: windows-win10), (-moz-os-version:windows-win10) {
> 	
> 	#main-window[sizemode="maximized"][tabsintitlebar] #titlebar {
> 	  margin-top: -1px !important;
> 	}
> }
> ```
> 
> to this:
> 
> ```css
> @media (-moz-platform: windows-win10), (-moz-os-version:windows-win10) {
> 	
> 	#main-window[sizemode="maximized"][tabsintitlebar] #titlebar {
> 	  margin-top: -3px !important;
> 	}
> }
> ```
> 
> The issue will be fixed on next update.

Thank you, the issue is gone in 4.3.2dev2

**Comment by Aris-t2** [comment] 2023-03-22 17:38
I think we can close this for now.

**Closed by Aris-t2** 2023-03-22 17:38 UTC
Labels: enhancement, WIP
